FROM ruby:2.6.3-alpine

RUN apk add --update build-base postgresql-dev libc-dev \
  linux-headers libxml2-dev libxslt-dev readline-dev tzdata

RUN rm -rf /var/lib/apk/*

RUN mkdir /var/devbox
WORKDIR /var/devbox
