FROM elixir:alpine

RUN apk add --update build-base postgresql-dev libc-dev \
  linux-headers libxml2-dev libxslt-dev readline-dev tzdata \
  git openssh

RUN rm -rf /var/lib/apk/*

RUN git config --global user.email "pavel@pravosud.com"
RUN git config --global user.name "Pavel Pravosud"

RUN mkdir /var/devbox
WORKDIR /var/devbox
