---
after_script:
- util/ci after_script
before_script:
- util/ci before_script
language: ruby
dist: trusty
sudo: required
branches:
  only:
    - master
    - auto
    - /^[\d.]+$/
    - /.+-stable$/
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.10
- 2.2.9
- 2.3.6
- 2.4.3
- 2.5.0
- ruby-head
env:
  - "TEST_TOOL=rubygems YAML=syck"
  - "TEST_TOOL=rubygems YAML=psych"
  - "TEST_TOOL=bundler RGV=master"
script:
  - util/ci script
matrix:
  allow_failures:
    - env: "TEST_TOOL=bundler RGV=master"
