" set up pathogen
source $DOTFILES_ROOT/vim/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect($DOTFILES_ROOT."/vim/bundle/{}")

" syntax highlighting
syntax on
filetype plugin indent on

" adequate tabs/spaces settings
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

" line numbers
set number

" display invisibles
set listchars=tab:▸\ ,eol:¬
set list!

" nice fonts for airline
let g:airline_powerline_fonts = 1

" highlight trailing whitespace
match ErrorMsg '\s\+$'

" kill trailing whitespace automatically
autocmd BufWritePre * :%s/\s\+$//e

" NotRocket command
command! -bar -range=% NotRocket :<line1>,<line2>s/:\(\w\+\)\s*=>/\1:/ge

" use Silver Searcher for ctrlp
let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
